services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 3

  sqs_ui:
    image: pacovk/sqs-admin:latest
    ports:
      - "3999:3999"
    environment:
      SQS_ENDPOINT_URL: http://localstack:4566
      SQS_AWS_REGION: ap-northeast-1
    depends_on:
      - localstack
